spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://data-gpt-postgres:5432/datagpt
    username: root
    password: root
  liquibase:
    enabled: true
openai:
  api-key: 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
tables: film,category,film_category
