spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://data-gpt-postgres:5432/datagpt
    username: root
    password: root
  liquibase:
    enabled: true
tables: address,articles,colors,customer,labels,order,order_positions,products,sizes,stock
openai:
  model: gpt-3.5-turbo
